version: "3.8"
services:
  web:
    image: shopping-cart-front
    networks:
      - app-network
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"

networks:
  app-network:
    external: true
